---
- name: download nagios core at dir "({{ local_cache_dir }}"
  get_url:
     url: https://assets.nagios.com/downloads/nagioscore/releases/{{ nagios_tgz_filename }}
     dest: "{{ local_cache_dir }}"
     mode: 0777

- name: "Extract from {{ local_cache_dir }}/{{ nagios_tgz_filename }} to {{ nagios_dir }}"
  unarchive:
    src:  "{{ local_cache_dir }}/{{ nagios_tgz_filename }}"
    dest: "{{ nagios_dir }}"
    remote_src: yes

- name: 
  command: ls -l {{ nagios_dir }}
  register: result

- debug:
    var: result.stdout_lines    

- name: configure nagios core
  command: "./configure --with-command-group=nagcmd"
  args:
    chdir: "{{nagios_core_dir}}"  
  register: result

- name: configarion output
  debug:
    var: result.stdout_lines

- name: run make all
  command: "make all"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install
  command: "make install"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install-init
  command: "make install-init"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install-commandmode
  command: "make install-commandmode"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install-config
  command: "make install-config"
  args:
    chdir: "{{nagios_core_dir}}"

- name: run make install-webconf
  command: "make install-webconf"
  args:
    chdir: "{{nagios_core_dir}}"

- name: adding mailid in nagios.conf file  
  lineinfile:
     path: "{{nagios_base_dir}}/etc/objects/contacts.cfg"
     regexp: "email "
     line: "    email            {{ nagios_email_address }}"
- name: passlib install
  command: "pip install passlib"

- name: "Setting password using htpasswd for {{nagios_admin_user}}"
  htpasswd:
    path: "{{nagios_base_dir}}/etc/htpasswd.users"
    name: "{{nagios_admin_user}}"
    password: "{{nagios_admin_pass}}"
    owner: nagios
    group: nagios
    mode: 0644

  notify: nagios apache2 restart  
- name: verifying nagios config files
  command: "{{ nagios_base_dir }}/bin/nagios -v {{ nagios_base_dir }}/etc/nagios.cfg"
  register: result
  notify: 
   - reload nagios
   - httpd start

- debug:
    var: result.stdout_lines
